### ISSUE TITLE
Incorrect normals calculations in DrawStuffOtk.cs (I've fixed it and included the fix in this Issue)

### ISSUE THREAD

**Issue by jabukufo** [notgiven688/jitterphysics#18]
The issue is that the normals calculations are incorrect, and cause triangle model lighting to be completely mangled. The problem lines are right here:

https://github.com/mattleibow/jitterphysics/blob/master/samples/JitterOpenGLDemo/JitterOpenGLDemo/DrawStuffOtk.cs#L928-L971

And the issue can be fixed by changing the selected lines above to:

https://pastebin.com/7uy1hufD

**Comment by na2axl** [comment]
@jabukufo why not a PR ?

**Comment by notgiven688** [comment]
The demo code will be updated anyway soon. But thank you for the fix. If you want to fix it in the current repo please provide a PR.
