### ISSUE TITLE
What is "not complete" about the 2D port?

### ISSUE THREAD

**Issue by waltdestler** [notgiven688/jitterphysics#23]
Hi, I'm wondering whether there's any information about what's "not complete" in this Jitter Physics 2D port? I'm currently trying to find an alternative to Farseer due to its lack of support for multiple cores and efficient compound shapes.

Thanks!

**Comment by mattleibow** [comment]
The 2D part was really just a plain import of the old code that I kept:
https://code.google.com/archive/p/jitterphysics/

> https://code.google.com/archive/p/jitterphysics/wikis/Jitter2D.wiki
> This is a port/modification of Jitter to just 2D. Once finished it will be much faster for 2D only simulations as opposed to using Jitter with constraints to keep everything on a 2D plane.

I have not done any testing at all and have no idea of the state.
