### ISSUE TITLE
Is running CollisionSystemPersistentSAP.DirtySortAxis on all three axis really need?

### ISSUE THREAD

**Issue by sophiepeithos** [notgiven688/jitterphysics#26]
inisde CollisionSystemPersistentSAP.DirtySortAxis it will do a exact intersection test when two are potentially intersected, or I overlook something?
thanks

**Comment by forestrf** [comment]
It sorts the array so that the next update needs the 3 arrays already sorted. Plus, the algorithm doesn't work when using only one axis because of how it adds and removes to the fullOverlaps list (I tested it the good old way by removing it, and it is needed)

**Comment by notgiven688** [comment]
In CollisionSystemPersistentSAP the axis check is done for all three axis. Correct. If I remember correctly the key to performance was to not bother checking the other two axis lists for overlap, but just check the bounding box; i.e. if a body overlaps on one axis, do the full check. So at first glance your comment is correct: why bothering checking all axis? The answer: removing a potential overlap is done, as soon as one axis reports separation.
