### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by edmand46** [notgiven688/jitterphysics#27]
Project abandoned?

**Comment by harryisgamer** [comment]
As far as I can tell, yes.

**Comment by wirmachenbunt** [comment]
is there any maintained .net physics project apart from bullet.

**Comment by na2axl** [comment]
Yes @wirmachenbunt, I can recommend you bepuphysics, it's an open source project on GitHub, heavily maintained and updated, and it's based on .NET Standard so it's cross platform (I've used this library several time and also for the game engine of my company)

**Comment by kascodingNL** [comment]
@na2axl it would be nice to mention it isn't really that easy to use.

**Comment by notgiven688** [comment]
Jitter physics is back to active development. Expect updates in the near future.
