### ISSUE TITLE
Is it possible to Save/Load world state?

### ISSUE THREAD

**Issue by MelnikovIG** [notgiven688/jitterphysics#28]
Is it possible to Save/Load world state? I tried to save some vectors and restore them later, but seems i missed something, so i am unable to restore state properly.

**Comment by notgiven688** [comment]
There is no such function build into the engine at the moment. As this engine is simulating classical physics it should be enough to store position (position and rotation) and momentum (velocity and angular velocity) of each RigidBody. There is one caveat: Jitter relies on contact caching over several frames, i.e. collision contacts get saved and reused. If you do not load/save these, the contact cache has to be rebuild which could make your scene unstable.
