### ISSUE TITLE
Jitter dimensions Vs Unity dimensions

### ISSUE THREAD

**Issue by RamonZoocha** [notgiven688/jitterphysics#30]
Thanks for this great library.

I'm building a game server with Jitter physics. The clients receive the objects' transform information from the server.

I don't know how to make an object on Unity match the size of its related Jitter rigidbody. For example: my sphere on the server has 0.5 radius. On Unity, the sphere object that receives its transform information also has 0.5. It SEEMS to match the dimension on the server, but I'm not sure, and it's hard to debug that. Is there an exact formula or anything like that?

**Comment by notgiven688** [comment]
I do not know the way you couple Jitter and Unity but a general answer is that you can choose whatever units you like. Jitter is mostly tuned in such a way, that most of your objects in the world should be of size "1" (e.g. a sphere with radius 0.5 is perfect). Also the default gravity is set to 9.81 which "fit" the gravitational acceleration on earth, if you choose your unit of length to be "meter" [m] and your unit of time to be "second" [s]. Other than that Jitter has no "intrinsic scale". If you create a sphere of radius 5 (in whatever units) in Unity, you can just ask Jitter to simulate a sphere of radius 5 in Jitter.
