### ISSUE TITLE
deterministic?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [notgiven688/jitterphysics#9]
```
Hi,

Just wondering if this physics engine is deterministic, at least on same 
platform???


Thanks!
```

Original issue reported on code.google.com by `atm...@gmail.com` on 27 Mar 2015 at 3:46

**Comment by dtandersen** [comment]
I don't think so, it uses floats. Checking out https://github.com/sam-vdp/bepuphysics1int.

**Comment by notgiven688** [comment]
@dtandersen is correct. It should be kind of deterministic on your system if you disable multithreading.
